[versions]
accompanist-permissions = "0.30.0"
android-gradle-plugin = "7.4.2"
androidx-activity = "1.7.0"
androidx-appcompat = "1.6.1"
androidx-compose-bom = "2023.03.00"
androidx-compose-compiler = "1.4.5"
androidx-core = "1.9.0"
androidx-fragment = "1.5.6"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.5.3"
androidx-test-core = "1.5.0"
androidx-test-espresso = "3.5.1"
androidx-test-fragment = "1.5.6"
androidx-test-junit = "1.1.5"
androidx-test-rules = "1.5.0"
camposer = "0.1.1"
chucker = "3.5.2"
coroutines = "1.6.4"
junit = "4.13.2"
kotlin = "1.8.20"
ksp = "1.8.20-1.0.10"
ktlint-plugin = "11.2.0"
leakcanary = "2.10"
material-components = "1.8.0"
maven-publish = "0.25.1"
mockk = "1.13.4"
moshi = "1.14.0"
moshix = "0.22.0"
moshi-lazy-adapters = "2.2"
okhttp = "4.10.0"
play-services-mlkit-face-detection = "17.1.0"
retrofit = "2.9.0"
sentry = "6.17.0"
timber = "5.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
moshix = { id = "dev.zacsweers.moshix", version.ref = "moshix" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-test-fragment" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
camposer = { module = "io.github.ujizin:camposer", version.ref = "camposer" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-noop = { module = "com.squareup.leakcanary:leakcanary-android-release", version.ref = "leakcanary" }
material-components = { module = "com.google.android.material:material", version.ref = "material-components" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-adapters-lazy = { module = "com.serjltt.moshi:moshi-lazy-adapters", version.ref = "moshi-lazy-adapters" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
play-services-mlkit-face-detection = { module = "com.google.android.gms:play-services-mlkit-face-detection", version.ref = "play-services-mlkit-face-detection" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
sentry = { module = "io.sentry:sentry" }
sentry-android-core = { module = "io.sentry:sentry-android-core" }
sentry-android-fragment = { module = "io.sentry:sentry-android-fragment" }
sentry-android-okhttp = { module = "io.sentry:sentry-android-okhttp" }
sentry-android-timber = { module = "io.sentry:sentry-android-timber" }
sentry-bom = { module = "io.sentry:sentry-bom", version.ref = "sentry" }
sentry-compose-android = { module = "io.sentry:sentry-compose-android" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
